FROM golang:1.14.6-alpine AS builder

WORKDIR /go/src/app

COPY . .

RUN CGO_ENABLE=0 GOOS=linux go build -ldflags="-s -w" src/main.go

RUN pwd
RUN ls -la
RUN ls -la src

#FROM scratch
#
#WORKDIR /go/src/app
#
#COPY --from=builder /go/src/app/main .

EXPOSE 8080

CMD ["./main"]
